import { useRef } from "react";

export default function PrintTransaction({ transaction, onClose }) {
  const printRef = useRef();

  const handlePrint = () => {
    const printContent = printRef.current;
    const printWindow = window.open('', '_blank');
    
    printWindow.document.write(`
      <html>
        <head>
          <title>Transaction Receipt - PharmaTrack</title>
          <style>
            body { font-family: Arial, sans-serif; margin: 20px; }
            .header { text-align: center; border-bottom: 2px solid #333; padding-bottom: 10px; margin-bottom: 20px; }
            .transaction-details { margin-bottom: 20px; }
            .item { display: flex; justify-content: space-between; margin-bottom: 10px; }
            .total { border-top: 2px solid #333; padding-top: 10px; font-weight: bold; font-size: 18px; }
            .footer { text-align: center; margin-top: 30px; font-size: 12px; color: #666; }
          </style>
        </head>
        <body>
          ${printContent.innerHTML}
        </body>
      </html>
    `);
    
    printWindow.document.close();
    printWindow.print();
    printWindow.close();
  };

  if (!transaction) return null;

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
      <div className="bg-white rounded-lg shadow-xl max-w-md w-full mx-4">
        <div className="px-6 py-4 border-b border-gray-200">
          <h3 className="text-lg font-semibold text-gray-900">Transaction Receipt</h3>
        </div>
        
        <div ref={printRef} className="px-6 py-4">
          <div className="header">
            <h1 className="text-2xl font-bold">💊 PharmaTrack</h1>
            <p>Pharmacy Management System</p>
            <p>Transaction Receipt</p>
          </div>
          
          <div className="transaction-details">
            <div className="item">
              <span>Transaction ID:</span>
              <span>#{transaction.id}</span>
            </div>
            <div className="item">
              <span>Date & Time:</span>
              <span>{new Date(transaction.date || Date.now()).toLocaleString()}</span>
            </div>
            <div className="item">
              <span>Medicine:</span>
              <span>{transaction.medicineName || "N/A"}</span>
            </div>
            <div className="item">
              <span>Quantity:</span>
              <span>{transaction.quantity || 0}</span>
            </div>
            <div className="item">
              <span>Unit Price:</span>
              <span>₹{transaction.unitPrice || 0}</span>
            </div>
            <div className="item total">
              <span>Total Amount:</span>
              <span>₹{transaction.totalPrice || 0}</span>
            </div>
          </div>
          
          <div className="footer">
            <p>Thank you for your business!</p>
            <p>Generated by PharmaTrack System</p>
          </div>
        </div>
        
        <div className="flex justify-end space-x-3 px-6 py-4 border-t border-gray-200">
          <button
            onClick={onClose}
            className="px-4 py-2 text-sm font-medium text-gray-700 bg-gray-100 hover:bg-gray-200 rounded-md transition duration-150 ease-in-out"
          >
            Close
          </button>
          <button
            onClick={handlePrint}
            className="px-4 py-2 text-sm font-medium text-white bg-blue-600 hover:bg-blue-700 rounded-md transition duration-150 ease-in-out"
          >
            Print Receipt
          </button>
        </div>
      </div>
    </div>
  );
}

